apiVersion: v1
kind: Namespace
metadata:
  name: lattice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lattice
  namespace: lattice
  labels:
    app: crystal
spec:
  selector:
    matchLabels:
      component: lattice
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: lattice
      labels:
        app: crystal
        component: lattice
    spec:
      containers:
        - name: lattice
          image: crystalimages.azurecr.io/sheb/lattice
          env:
            - name: RUST_LOG
              value: info

            - name: PROD_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lattice-postgres
                  key: postgres-connection-url
